export const EXPECTED_FIELD_POINTERS = {
  "s0.workload.message_size_multiplier": "/overrides/workload/message_size_multiplier",
  "s1.runtime.batch_scheduler": "/overrides/runtime/batch_scheduler",
  "s1.runtime.max_batch_size": "/overrides/runtime/max_batch_size",
  "s1.runtime.kv_capacity_tokens": "/overrides/runtime/kv_capacity_tokens",
  "s6.fabric.scale_up_bandwidth_gbps": "/overrides/fabric/scale_up_bandwidth_gbps",
  "s6.fabric.scale_up_latency_us": "/overrides/fabric/scale_up_latency_us",
  "s6.fabric.scale_out_bandwidth_gbps": "/overrides/fabric/scale_out_bandwidth_gbps",
  "s6.fabric.scale_out_latency_us": "/overrides/fabric/scale_out_latency_us",
} as const;

export type CurrentSubsetFieldId = keyof typeof EXPECTED_FIELD_POINTERS;

export const FIELD_ALIASES: Readonly<Record<CurrentSubsetFieldId, readonly string[]>> = {
  "s0.workload.message_size_multiplier": [
    "message size multiplier",
    "message multiplier",
    "message size",
    "communication load multiplier",
    "通信负载倍率",
    "消息大小倍率",
    "消息倍率",
    "报文倍率",
  ],
  "s1.runtime.batch_scheduler": [
    "batch scheduler",
    "scheduler policy",
    "scheduler",
    "fifo",
    "decode priority",
    "fabric backpressure aware",
    "批调度器",
    "批调度",
    "调度策略",
    "先进先出",
    "解码优先",
    "网络反压感知",
  ],
  "s1.runtime.max_batch_size": [
    "maximum batch size",
    "max batch size",
    "max batch",
    "batch size",
    "最大批大小",
    "最大 batch",
    "最大batch",
  ],
  "s1.runtime.kv_capacity_tokens": [
    "kv capacity tokens",
    "kv token capacity",
    "kv capacity",
    "kv cache capacity",
    "kv容量token",
    "kv token容量",
    "kv容量",
    "kv cache容量",
  ],
  "s6.fabric.scale_up_bandwidth_gbps": [
    "scale-up bandwidth",
    "scale up bandwidth",
    "scaleup bandwidth",
    "纵向扩展网络带宽",
    "纵向扩展带宽",
    "纵向带宽",
    "scale-up 带宽",
  ],
  "s6.fabric.scale_up_latency_us": [
    "scale-up latency",
    "scale up latency",
    "scaleup latency",
    "纵向扩展网络时延",
    "纵向扩展时延",
    "纵向延迟",
    "scale-up 延迟",
  ],
  "s6.fabric.scale_out_bandwidth_gbps": [
    "scale-out bandwidth",
    "scale out bandwidth",
    "scaleout bandwidth",
    "横向扩展网络带宽",
    "横向扩展带宽",
    "横向带宽",
    "scale-out 带宽",
  ],
  "s6.fabric.scale_out_latency_us": [
    "scale-out latency",
    "scale out latency",
    "scaleout latency",
    "横向扩展网络时延",
    "横向扩展时延",
    "横向延迟",
    "scale-out 延迟",
  ],
};

export const UNSUPPORTED_CAPABILITIES = [
  { pattern: /(?:model|模型|llama|qwen|70b)/iu, capability: "model_selection", gap_id: "GAP-MODEL-001" },
  {
    pattern: /(?:h100|a100|device|gpu\s*(?:type|model)|卡型|设备型号)/iu,
    capability: "device_selection",
    gap_id: "GAP-DEVICE-001",
  },
  {
    pattern: /(?:\d+\s*(?:张|块)\s*(?:(?:卡|gpu)|(?:h|a)\d{2,4})|gpu\s*count|device\s*count|卡数)/iu,
    capability: "device_count",
    gap_id: "GAP-DEVICE-001",
  },
  {
    pattern: /(?:\btp\b|tensor\s*parallel|张量并行)/iu,
    capability: "tensor_parallel_degree",
    gap_id: "GAP-PARALLEL-001",
  },
  {
    pattern: /(?:\bpp\b|pipeline\s*parallel|流水线并行)/iu,
    capability: "pipeline_parallel_degree",
    gap_id: "GAP-PARALLEL-001",
  },
  {
    pattern: /(?:\bep\b|expert\s*parallel|专家并行)/iu,
    capability: "expert_parallel_degree",
    gap_id: "GAP-PARALLEL-001",
  },
  { pattern: /(?:placement|放置|映射到设备)/iu, capability: "placement", gap_id: "GAP-PARALLEL-001" },
  {
    pattern: /(?:physical\s*kv|kv\s*page|kv\s*block|物理\s*kv|kv\s*页|kv\s*块)/iu,
    capability: "physical_kv_policy",
    gap_id: "GAP-KV-001",
  },
  {
    pattern: /(?:collective|all-?reduce|all-?to-?all|集合通信算法)/iu,
    capability: "collective_algorithm",
    gap_id: "GAP-PARALLEL-001",
  },
  { pattern: /(?:\bslo\b|ttft|tpot|p99|服务等级)/iu, capability: "slo", gap_id: "GAP-SLO-001" },
  {
    pattern: /(?:create\s+(?:a\s+)?run|start\s+(?:the\s+)?run|创建运行|启动运行|执行实验)/iu,
    capability: "create_run",
    gap_id: "GAP-APPROVAL-001",
  },
  { pattern: /(?:cancel\s+(?:the\s+)?run|取消运行|取消任务)/iu, capability: "cancel", gap_id: "GAP-CANCEL-001" },
  {
    pattern: /(?:previous\s+turn|next\s+turn|上一轮|下一轮|多轮)/iu,
    capability: "conversation",
    gap_id: "GAP-CONV-001",
  },
] as const;
